# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/xiaoxin682276"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/700819964?spm_id_from=333.1007.0.0"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "t.me/xiaoxin682276"

[social.params]
icon = "brand-telegram"